# Tname: Unzip Files

on:
  push:
    paths:
      - '*.zip'  # Kích hoạt khi có file ZIP được đẩy lên

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Unzip the file
        run: unzip <Profile-Resource-V3-.zip>.zip -d <output-directory>
